### ISSUE TITLE
Alert for safe files

### ISSUE THREAD

**Issue by goochi1** [airbnb/binaryalert#104]
## Background

Run Binaryalert fine

## Desired Change

Need it to be able to send an alert if file is clean as well as if it has a virus. is this possible?

**Comment by austinbyers** [comment]
Good question. So you want a notification sent to the `binaryalert_alerts` SNS topic for clean results as well as yara matches? Or would you like to be able to invoke the analyzer directly and have it return Pass/Fail?

Can you describe your use case a little bit to help us understand how best to address this?

**Comment by goochi1** [comment]
Yes so once the file has been notes as 'clean' it would send an notification to the topic that we can use to make the document as available.
Likewise i would like to be able to get a notification what it matches the rules so we can investigate the file.

**Comment by austinbyers** [comment]
Good idea - perhaps we could support another SNS topic for "clean" notifications. Users could specify either the same or a different one.

Anything which is an environment variable for the Lambda functions (including `YARA_ALERTS_SNS_TOPIC_ARN`) is defined in Terraform. In this case, [terraform/lambda.tf#106](https://github.com/airbnb/binaryalert/blob/master/terraform/lambda.tf#L103-L107)

**Comment by goochi1** [comment]
Yes thats what i have been working on adding so far. Changed it so i get 2 different emails from the same topic but idealy need a new topic. which i have made but its just getting a new thing such as YARA_SAFE_SNS_TOPIC_ARN

**Comment by goochi1** [comment]
Hitting a snag and would be good to get your opinion. Tried committing a branch but its not allowing me too

**Comment by austinbyers** [comment]
The easiest thing to do is to fork the BinaryAlert repo. Then you can commit changes to it as you see fit. If you have a branch you'd like to merge upstream (to the original repo), you can submit a pull request.

Does that make sense? So instead of committing directly to BinaryAlert (which is restricted), you can submit a pull request from your own forked repo

**Comment by austinbyers** [comment]
It's also worth remembering that the SNS alert format includes a `NumMatchedRules` top-level key. So another approach (instead of creating a separate topic) is that you could alert the same topic, but set `NumMatchedRules == 0`, which downstream applications can check.

**Comment by goochi1** [comment]
So i am trying to extract just the terrafrom from this to run in my infrastructure however when i do it the bit i added, to send safe messages, doesn't work. it does when i do all the manage.py etc but not just with the created files, any ideas?

**Comment by goochi1** [comment]
Hi Austin, hope you are well.
i have put my code into this repo https://github.com/goochi1/binaryalert 
what is the best way of me sharing with you?

**Comment by austinbyers** [comment]
Up to you! I can see your repo, so I can manually merge your change in the next BA release. Or, you can create a PR to merge your `add_safe_alert` branch into the BinaryAlert master branch:

https://github.com/airbnb/binaryalert/compare/master...goochi1:task/steph_add_safe_alert?expand=1

And I'll review the PR!
