### ISSUE TITLE
Error loading configuration issue

### ISSUE THREAD

**Issue by boodera** [airbnb/binaryalert#111]
## Background

I followed the steps for deployment of binaryalert using ubuntu based EC2 instance, with all configurations done. When I ran './manage.py deploy' , it displayed this error

> Error loading configuration: Error loading /home/ubuntu/binaryalert/terraform/cloudwatch_dashboard.tf: Error reading config for aws_cloudwatch_dashboard[binaryalert]: local.dashboard_body: resource variables must be three parts: TYPE.NAME.ATTR in:
> ${local.dashboard_body}
> Traceback (most recent call last):
>   File "./manage.py", line 488, in <module>
>     main()
>   File "./manage.py", line 484, in main
>     manager.run(args.command)
>   File "./manage.py", line 348, in run
>     getattr(self, command)()  # Command validation already happened in the ArgumentParser.
>   File "./manage.py", line 421, in deploy
>     self.apply()
>   File "./manage.py", line 372, in apply
>     subprocess.check_call(['terraform', 'init'])
>   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['terraform', 'init']' returned non-zero exit status 1.

Can you please suggest any configuration mistake I may have done, or is it a known bug?

**Comment by austinbyers** [comment]
Hi @boodera! I don't think we've seen this before. My guess is that you're running an older version of Terraform. What version of Terraform are you running? `terraform --version` Try upgrading to the latest version (0.11.X).

You can test whether Terraform understands the config by `cd terraform && terraform validate`

**Comment by austinbyers** [comment]
I'm closing the issue for now, but feel free to re-open if you're still experiencing any issues!
