### ISSUE TITLE
Add CarbonBlack downloader function

### ISSUE THREAD

**Issue by austinbyers** [airbnb/binaryalert#29]
Provide a downloader function which copies binaries from CarbonBlack into the BinaryAlert S3 bucket. This makes it easier for CarbonBlack customers to copy over both their existing and future CarbonBlack binaries.

**Comment by mime-frame** [comment]
@austinbyers morning! where are we on this?

**Comment by austinbyers** [comment]
Working on it now! Should have it out in v0.11 within a day or two
