### ISSUE TITLE
internal error: 34: Error

### ISSUE THREAD

**Issue by mime-frame** [airbnb/binaryalert#45]
Note: This issue was created for posterity purposes only.

Usually this error will happen if one of your YARA rules is using a module that isn’t yet supported.

Ex: `import "hash"` - hash isn't supported (yet)

If you're not doing this, file a new bug as it's likely something else :)

**Comment by austinbyers** [comment]
We'll make sure to include a Troubleshooting section in the upcoming documentation (issue #2 )

Hash support: Issue #30
