### ISSUE TITLE
Provide a tightly scoped IAM policy for deployment user

### ISSUE THREAD

**Issue by maestretti** [airbnb/binaryalert#67]
Documentation currently asks for rather broad permissions for the IAM User that will deploy BinaryAlert. We would like an IAM policy file scoped to the minimum privileges required to successfully deploy.

**Comment by austinbyers** [comment]
Good call! I'll look at this as soon as I get a chance (likely next week).

Minimum deploy privileges will not include, for example, being able to see the generated CloudWatch dashboard. Also, if a deploy significantly changes the existing infrastructure (e.g. changing the `name_prefix`), you would need `Destroy` permissions as well.

**Comment by maestretti** [comment]
@mikegrima is looking into it on our side as well. Let us know if we can help!

**Comment by maestretti** [comment]
Here are the events we logged in CloudTrail during deploy. As you mentioned in your comment the initial deploy, or a major change / removal, may require significantly more permissions than a redeploy for a code update. It could warrant two different roles I suppose to really keep things tight. 

"eventName: Descending",Count
getcalleridentity,64
describeaccountattributes,32
getuser,32
decrypt,26
describealarms,22
describetable,12
getrole,12
putmetricalarm,11
getfunction20150331v2,7
listversionsbyfunction20150331,7
describeloggroups,6
getalias20150331,6
listattachedrolepolicies,6
listtagsloggroup,6
getbucketcors,4
getbucketlifecycle,4
getbucketlocation,4
getbucketlogging,4
getbucketreplication,4
getbucketrequestpayment,4
getbuckettagging,4
getbucketversioning,4
getbucketwebsite,4
gettopicattributes,4
attachrolepolicy,3
createalias20150331,3
createfunction20150331,3
creategrant,3
createloggroup,3
createrole,3
describekey,3
encrypt,3
getrolepolicy,3
putretentionpolicy,3
putrolepolicy,3
putrule,3
tagloggroup,3
createbucket,2
createtopic,2
describetimetolive,2
getbucketnotification,2
listtagsofresource,2
putbucketacl,2
putbucketlifecycle,2
putbucketlogging,2
putbuckettagging,2
putbucketversioning,2
setqueueattributes,2
addpermission20150331v2,1
createpolicy,1
createtable,1
describerule,1
enablerule,1
getpolicy,1
getpolicy20150331v2,1
getpolicyversion,1
listtargetsbyrule,1
putbucketnotification,1
putdashboard,1
puttargets,1
tagresource,1
updatealias20150331,1
