### ISSUE TITLE
Analyzer should pull bucket from event, not environment variables

### ISSUE THREAD

**Issue by austinbyers** [airbnb/binaryalert#72]
## Background

Right now, the analyzer uses `os.environ['S3_BUCKET_NAME']` to determine which bucket to download binaries from. The problem with this approach is that the analyzer can never be invoked for any other bucket. If the bucket name were pulled from the event notification instead of an environment variable, the analyzer could be invoked directly for any S3 object.

In particular, this would make it easy for users to manually add event notifications for their existing S3 buckets.

## Desired Change

Use the bucket name from the event notification instead of an environment variable.

**Comment by austinbyers** [comment]
The documentation should be updated with instructions on how to use BinaryAlert to analyze existing S3 buckets

**Comment by rafalyesware** [comment]
@austinbyers it looks like hooking up the events works great, but I'm having trouble with the `analyze_all` invocation on a different bucket.. basically cloned a batcher and its' associated policies and hooked it up to an existing bucket.  However, every attempt to run it is failing with a AccessDenied for `ListObjectsV2`.

Also, for all this stuff, there doesn't seem to be a clean way to add configuration for an alternate bucket without editing all the BinaryAlert files in the source tree.  Thoughts on this also welcome.

**Comment by austinbyers** [comment]
@rafalyesware You're right - there's no clean way to specify multiple/alternate buckets at the moment. Can you share a little bit more about your use case? Do you have multiple S3 buckets that you want to send to BinaryAlert, and then the batcher would enqueue the objects in all of the different buckets? Do you use the auto-created BinaryAlert bucket in addition to existing ones?

I'm happy to add something to help with this in the next upcoming BA release if it's relatively straightforward, which it sounds like it might be.

In the meantime, the batcher permissions you're talking about are defined here: https://github.com/airbnb/binaryalert/blob/5a35e019c4c8ef53fb5be4bdb5a797d69fa4ef11/terraform/lambda_iam.tf#L73-L102

You'll need to modify those permissions to add a statement to list buckets in your existing S3 bucket

**Comment by austinbyers** [comment]
You can also modify the Batcher environment variables so that the batcher looks at a different bucket:

https://github.com/airbnb/binaryalert/blob/cebb706fa1736888accf1467528b9f860c683530/terraform/lambda.tf#L45-L51

Changing the `S3_BUCKET_NAME` environment variable, combined with the new permissions, should work (and then you wouldn't need to make a new batcher function).

**Comment by rafalyesware** [comment]
Thanks for the feedback @austinbyers. It doesn't look like that policy is used anywhere, at least in `master`...

As for my use case, I could get by on just overriding the default bucket make but thought it would be good to keep that for at the very least testing.

**Comment by austinbyers** [comment]
Each lambda function needs its own policies to interact with the various AWS resources, and those policies are all defined in `terraform/lambda_iam.tf`, which are attached to the Lambda execution role
