### ISSUE TITLE
support for terraform 11

### ISSUE THREAD

**Issue by robomotic** [airbnb/binaryalert#77]
## Background

The latest version of terraform is 11.0. When I attempt a deploy I get:

>$ ./manage.py deploy
> ......................................................................
> ----------------------------------------------------------------------
> Ran 70 tests in 3.314s
> 
> OK
> Creating analyzer deploy package...
> Creating batcher deploy package...
> Creating dispatcher deploy package...
> Initializing modules...
> - module.binaryalert_downloader
> - module.binaryalert_batcher
> - module.binaryalert_dispatcher
> - module.binaryalert_analyzer
> The currently running version of Terraform doesn't meet the
> version requirements explicitly specified by the configuration.
> Please use the required version or update the configuration.
> Note that version requirements are usually set for a reason, so
> we recommend verifying with whoever set the version requirements
> prior to making any manual changes.
> 
>   Module: root
>   Required version: ~> 0.10.4
>   Current version: 0.11.0
> 

## Desired Change

Would it be possible to convert the terraform scripts to be able to run with version 0.11.0 ?

Cheers.

**Comment by robomotic** [comment]
For the OSX brew users out there I have created a fork with the old version here:
[https://github.com/robomotic/homebrew-core/blob/master/Formula/terraform.rb](url)
So you can install it by doing:
brew install https://raw.githubusercontent.com/robomotic/homebrew-core/master/Formula/terraform.rb

**Comment by austinbyers** [comment]
Way to be on the cutting edge - Terraform v0.11 came out just 4 days ago!

We will definitely add this to the next release of BinaryAlert
