### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jjjan** [airbnb/binaryalert#9]
Hello, is there any way to have running this service on On-premises instead of AWS.
because i don't have it. my goal is to capture binary file and i do analysis on other platform.
any idea?

**Comment by austinbyers** [comment]
Hi @jjjan,

BinaryAlert just analyzes files which you upload to an S3 bucket; those files could be anything you want and could come from anywhere.

If you're looking for a way to capture binaries from endpoints, [osquery](https://osquery.io/) is an open-source project that [supports file carving](https://osquery.io/docs/tables/#carves). You can also use an enterprise endpoint solution like [CarbonBlack](https://www.carbonblack.com/).

Let me know if that answers your question!

**Comment by jjjan** [comment]
Great. thanks for suggestion about osquery. but is there any solution to analysis my file without S3 bucket. for example i upload my file on our server and then analysis that?

**Comment by austinbyers** [comment]
You can always [install YARA yourself](http://yara.readthedocs.io/en/v3.6.3/gettingstarted.html#getting-started) and run it locally: `yara rules.yara myfile`

**Comment by jjjan** [comment]
indeed. and your benefits of project is that's real time but need AWS. at least i make suggest to support On-premises instead of AWS. thanks for attention.
