### ISSUE TITLE
manage.py run issue

### ISSUE THREAD

**Issue by goochi1** [airbnb/binaryalert#97]
## Background

running manage.py configue and getting the following error:

UK-C02T55NPFVH4:binaryalert sgooch$ python ./manage.py configure
  File "./manage.py", line 60
    def _get_input(prompt: str, default_value: str) -> str:

**Comment by austinbyers** [comment]
Hi @goochi1! Are you running with Python3 in a virtualenv?

If the [Getting Started](https://binaryalert.io/getting-started.html) documentation doesn't fix the problem, let me know and I'd be happy to help!
